// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4XlhvLaIn78rZKrKcD4Lvts5EMR5uBdE',
    appId: '1:346996712214:web:d65fc375c5336a190ee637',
    messagingSenderId: '346996712214',
    projectId: 'appifysocm',
    authDomain: 'appifysocm.firebaseapp.com',
    storageBucket: 'appifysocm.appspot.com',
    measurementId: 'G-TF251X3V95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1I0XMDfeDqDtj8uZNcw_jrGEc-BXH_Vg',
    appId: '1:346996712214:android:931e9224783ee38d0ee637',
    messagingSenderId: '346996712214',
    projectId: 'appifysocm',
    storageBucket: 'appifysocm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWGLeG_aDA5em_P_qKY9BKD56XUOG1UcE',
    appId: '1:346996712214:ios:caed65faf2d14d730ee637',
    messagingSenderId: '346996712214',
    projectId: 'appifysocm',
    storageBucket: 'appifysocm.appspot.com',
    iosBundleId: 'com.sif.appifyLabSocm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWGLeG_aDA5em_P_qKY9BKD56XUOG1UcE',
    appId: '1:346996712214:ios:9a03582f1a6a381c0ee637',
    messagingSenderId: '346996712214',
    projectId: 'appifysocm',
    storageBucket: 'appifysocm.appspot.com',
    iosBundleId: 'com.sif.appifyLabSocm.RunnerTests',
  );
}
